build.sh

This seems to work, and I'm already using builds for ubuntu 16.04. I haven't tried ubuntu 14.04. 
I'll really appreciate your feedback!

Self host llvm

---

.travis.yml
README.md
travis.sh

Added support to build `cxx-common` on OS X with Homebrew.

Support for OS X with Homebrew

---

travis.sh

* Build with clang and not base GCC to fix "upgrade your gcc" message
* Install Z3 since some clang builds want it.

Fix travis builds

---

travis.sh

* Fixes for ubuntu 14.04 and it's lack of z3

Fix Travis, Take 2

---

.dockerignore
Dockerfile.aarch64
pkgman/installers/common.py

* Dockerfile for aarch64 builds
* Should be parametrized enough to adapt to multiple Ubuntus and LLVM revisions, and probably x86-64

Aarch64 Dockerfile Builds

---

.github/workflows/ci.yml
Dockerfile
pkgman.py

Fix ubuntu 20.04 image build

---

.github/workflows/ci.yml

* Attempt to automatically publish binary releases via GH Actions

Attempting to push releases via GH Actions

---

.github/workflows/ci.yml

* Attempting to start auto incrementing version numbers for releases via actions

Set version number for GH release tag

---

.github/workflows/ci.yml
pkgman/installers/common.py

Add LLVM10 builds for cxx-common

Support for LLVM10

---

Dockerfile

More stages for logical separation resulting in smaller final images

Smaller final docker image

---

.github/workflows/ci.yml
Dockerfile
pkgman/installers/common.py

Updating to LLVM11 now that its been released.

Remove llvm8 and ubuntu 19.10; add llvm11

---

.github/workflows/vcpkg_ci_mac.yml

Specify llvm version for packaged remill mac

---

README.md
build_dependencies.sh

Also updated some of the docs
closes #664

Allow for export directory of built dependencies in build script

---

.github/workflows/vcpkg_ci_windows.yml

Use cmd.exe to prevent zombie msvc processes

---

docker/Dockerfile.ubuntu.vcpkg

Required for vcpkg tool from source

Install latest CMake 3.21.1 in Docker images

---

.github/workflows/vcpkg_ci_linux.yml
.github/workflows/vcpkg_ci_mac.yml
.github/workflows/vcpkg_ci_windows.yml
README.md
ports/llvm-13/0001-fix-install-paths.patch
ports/llvm-13/0002-fix-openmp-debug.patch
ports/llvm-13/0003-fix-dr-1734.patch
ports/llvm-13/0004-fix-tools-path.patch
ports/llvm-13/0005-fix-compiler-rt-install-path.patch
ports/llvm-13/0006-fix-tools-install-path.patch
ports/llvm-13/0020-remove-FindZ3.cmake.patch
ports/llvm-13/0021-fix-FindZ3.cmake.patch
ports/llvm-13/0022-llvm-config-bin-path.patch
ports/llvm-13/0023-clang-sys-include-dir-path.patch
ports/llvm-13/CONTROL
ports/llvm-13/portfile.cmake
ports/llvm-vcpkg-common/llvm-common-build.cmake

Initial support for upcoming LLVM 13.

LLVM 13 support

---

.github/workflows/vcpkg_ci_linux.yml
.github/workflows/vcpkg_ci_mac.yml
.github/workflows/vcpkg_ci_windows.yml
.gitmodules

We don't have enough time to support the required changes as
dependencies are updated. Anvill and rellic are receiving more
development effort at this time

Remove McSema from testing

---

ports/llvm-12/vcpkg.json
ports/llvm-13/vcpkg.json

This should provide things like FileCheck for lit testing

Install LLVM utils tools

---

.github/workflows/vcpkg_docker_amd64.yml
.github/workflows/vcpkg_docker_arm64.yml

* Move ARM64 docker image generation to AWS

Use AWS for arm64 docker images

---

vcpkg_info.txt

Prepping for asan fixes and xed fixes in other PRs

Update vcpkg to latest commit

---

toolchain/vcpkg_unix_sanitizer_toolchain.cmake
triplets/arm64-osx-asan.cmake
triplets/x64-linux-asan.cmake
triplets/x64-linux-rel-asan.cmake
triplets/x64-osx-asan.cmake
triplets/x64-osx-rel-asan.cmake

Use toolchain for asan flag overriding

---

docker/Dockerfile.ubuntu.vcpkg

Also bumped to the default compiler, hopefully it does not break anyone else's projects

Add clang-14 to docker container

---

.github/workflows/vcpkg_docker_arm64.yml

fix docker workflow

---

dependencies.txt
ports/re2c/portfile.cmake
ports/re2c/vcpkg.json

* Added re2c
* Added dependencies for lifting-bits/gap

Add new dependencies
