lifting-bits/cxx-common

.github/workflows/ci.yml
pkgman/installers/common.py

* MacOS: Give libcxx a `CMAKE_INSTALL_PREFIX` so it doesn't try to write to `/usr/local` without root
* Add ubuntu 19.10 and 20.04 to build matrix, remove 16.04

Attempt to fix MacOS and to try on ubuntu 20.04 and 19.10

---

pkgman/installers/common.py

Get the exact python3 executable first and fallback to python3 if not found.

Check for the python3 version

---

.github/workflows/ci.yml
Dockerfile
README.md

* Remove 'arch' parameter from Dockerfile
* Update documentation to reflect that its gone

Remove unused arch parameter

---

Dockerfile
pkgman.py
pkgman/installers/common.py
pkgman/installers/utils.py
travis.sh

* Ninja instead of Makefiles for Linux on LLVM
* Enable ccache on LLVM [more work to do on this one to use cache on rebuilds]
* New supported LLVM targets: ARMv7 and NVPTX

Build Improvements

---

Dockerfile
pkgman/installers/common.py

* Do not build CapnProto or Capstone  (but keep their build setups)
* Start building Z3 from source (Used in Rellic)

Remove capnp and capstone, add z3

---

Dockerfile
pkgman.py
pkgman/installers/common.py
pkgman/patches/FindZ3.cmake
pkgman/patches/testz3.cpp

* Patch LLVM to find a static Z3 lib
* Link to our own Z3
* Ensure that if llvm and z3 are built, z3 is done first

Use our own Z3 if available

---

pkgman/installers/common.py

Ensure we do not accidentally link against packaged z3 libs

Help older LLVMs find our Z3

---

pkgman/patches/FindZ3.cmake

* Avoid emitting full paths in LLVMExports.cmake

Avoid exporting a full file path for Z3 in cmake

---

pkgman/installers/unix.py
pkgman/installers/windows.py

Bump CMake version to 3.17.2

---

.github/workflows/ci.yml
Dockerfile
pkgman/installers/common.py
pkgman/installers/unix.py
pkgman/installers/utils.py
travis.sh

Uses ccache to build a cache directory in the repo root at `cache`.
ccache cache is stored in `cache/ccache`, in case we want to cache downloads in the same directory in the future.

CI Build caching

---

vcpkg_info.txt

New protobuf fixes some CMake bugs.
If you want to regularly build from source, I would suggest using `ccache`(and upping the cache size limit to maybe 20GB if you want to build multiple LLVM versions and possibly debug versions as well) to speed up compilation of packages that haven't been upgraded:
```
export CMAKE_C_COMPILER_LAUNCHER="$(which ccache)"
export CMAKE_CXX_COMPILER_LAUNCHER="$(which ccache)"
./build_dependencies.sh --release llvm-10
```
The reason for needing to rebuild everything is because vcpkg hashes all of the script files used to process each package definition and encodes this when building and caching the results. This is to ensure that there are no breaking changes between script modifications when building new packages or reusing installed packages.
I'll add this …

Bump vcpkg protobuf

---

build_dependencies.sh

Issue:
1. With the new vcpkg build system, g++ 10.2.0 has trouble building
llvm-10, generating an error `/usr/bin/ld.gold: internal error in open,
at /build/binutils/src/binutils-gdb/gold/descriptors.cc:99` while
linking `lib/libclang-cpp.so.10`. So it may be advisable to use Clang
as the default compiler in the build script, in addition to setting
it in the dockerfile.
2. The permission of the `protoc` tool built by vcpkg is 774. If we
follow the typical way of building software by building it without
privilege and installing it with privilege, there will be a
"permission denied" error when we are building McSema.

Use clang as the default compiler if available, and fix the protoc permission issue

---

build_dependencies.sh
ports/llvm-10/portfile.cmake
ports/llvm-11/portfile.cmake
ports/llvm-9/portfile.cmake

* Do not override CC/CXX if already set
* Check for program pre-requisites prior to building
* Use the `lld` linker on Clang+Linux builds (Closes #670)

Build Updates

---

ports/z3/portfile.cmake

Make z3 use py3 to avoid having an un-needed dependency on py2. This change is already in the windows branch, but running into issues where it would be helpful on its own.

Bump z3 to python3

---

.github/workflows/vcpkg_ci_mac.yml

MacOS 11 runners are unstable and often fail to start.
Updated XCode to latest stable version

Revert to using MacOS 10.15 runner with XCode 12.4

---

ports/llvm-10/CONTROL
ports/llvm-11/CONTROL
ports/llvm-12/0001-fix-install-paths.patch
ports/llvm-12/0002-fix-openmp-debug.patch
ports/llvm-12/0003-fix-dr-1734.patch
ports/llvm-12/0004-fix-tools-path.patch
ports/llvm-12/0005-remove-FindZ3.cmake.patch
ports/llvm-12/0006-fix-FindZ3.cmake.patch
ports/llvm-12/0007-clang-sys-include-dir-path.patch
ports/llvm-12/CONTROL
ports/llvm-12/LICENSE
ports/llvm-12/NOTICE
ports/llvm-12/portfile.cmake
ports/llvm-9/CONTROL
ports/llvm-vcpkg-common/llvm-common-build.cmake

The changes add port files to build llvm 12. It also enables the exception handler which is required to build alive2.

llvm12 build support

---

ports/llvm-10/CONTROL
ports/llvm-11/CONTROL
ports/llvm-12/CONTROL
ports/llvm-9/0010-compiler-rt-glibc-2.31.patch
ports/llvm-9/CONTROL
ports/llvm-9/portfile.cmake

Build LLVM compiler-rt by default for toolchain sanitizer support

---

.github/workflows/vcpkg_ci_windows.yml

Occasionally vcpkg bootstrap will hang for 6 hours asking if we want to terminate. We say "yes" because we do a retry until the binary shows up.

windows,ci: Fix vcpkg bootstrap confirmation

---

.github/workflows/vcpkg_ci_windows.yml

For some reason the bootstrap script is very flaky. Let's just manually keep track of it

Use timeout for windows bootstrap

---

build_dependencies.sh
ports/xed/portfile.cmake
triplets/arm64-osx-asan.cmake

Hi @ekilmer. I'm on an M1 Mac and had to make these changes to get `cxx-common` building.
I only added an ASan configuration since that's the one I intended to build. I can add others too like `arm64-osx-rel.cmake` but it will take me a while to verify them since the build takes ages.

Get ASan builds working for M1 Mac

---

ports/llvm-10/0026-fix-missing-header-limits.patch
ports/llvm-10/portfile.cmake
ports/llvm-11/0025-fix-missing-header-limits.patch
ports/llvm-11/portfile.cmake
ports/llvm-9/0029-fix-missing-header-limits.patch
ports/llvm-9/portfile.cmake

* LLVM patch: https://github.com/llvm/llvm-project/commit/b498303066a63a203d24f739b2d2e0e56dca70d1

[llvm 9,10,11] Fix missing header (#820)

---

ports/z3/CONTROL
ports/z3/fix-cmake-flags.patch
ports/z3/portfile.cmake

Bumping the z3 version for performance in anvill

Bump z3 version

---

docker/Dockerfile.ubuntu.vcpkg

Remove --no-install-recommends from apt install. It saved a bit of space
but it doesn't matter if we can't reliably install the dependencies

Docker: Fix issue with unment dependencies

---

ports/llvm-12/vcpkg.json
ports/llvm-13/vcpkg.json

Build cxx-common architecture targets when building llvm via vcpkg.json. Fixes the issue where our tools can't link against things like `libLLVMAArch64*`

Build cxx-common architecture targets

---

README.md
build_dependencies.sh

THe previous logic was very complex and didn't account for weird
situations. Just remove the complexity in favor of telling users to
start fresh

Simplify build script

---

dependencies.txt

Added support for packaging rocksdb with cxx-common.

Added support for rocksdb

---

triplets/arm64-osx-asan.cmake
triplets/x64-linux-rel-asan.cmake
triplets/x64-osx-rel-asan.cmake

There were errors in LLVM without this

Always add sanitizer flag when linking

---

ports/llvm-13/0024-remove-elf_relocation-checks.patch
ports/llvm-13/portfile.cmake
ports/llvm-13/vcpkg.json
triplets/arm64-osx-asan.cmake

Im not happy merging this as is because it skips relocations that it is unable to apply in elfs without applying them. This should probably be gated behind a feature or something

add LLVM relocation patch

---

ports/xed/portfile.cmake
ports/xed/vcpkg.json
vcpkg_info.txt

Now we build with the selected compiler instead of whatever mbuild was
picking up. We also correctly add the requested vcpkg flags, which
affects the sanitizer build(s).
depends on #924

Correctly pass all vcpkg flags to XED buildsystem

---

.github/workflows/vcpkg_ci_aws_amd64.yml
.github/workflows/vcpkg_ci_aws_arm64.yml
.github/workflows/vcpkg_ci_mac.yml
.github/workflows/vcpkg_ci_windows.yml
ports/z3/portfile.cmake
ports/z3/vcpkg.json

Python2 is EOL and the Z3 scripts work with both Python2 and Python3, so
we prefer Python3

z3: vcpkg find Python3 instead of Python2

---

ports/llvm-13/portfile.cmake
ports/llvm-13/vcpkg.json
ports/llvm-14/0021-fix-find_dependency.patch
ports/llvm-14/portfile.cmake
ports/llvm-14/vcpkg.json

Any chance we can add some automatic check mechanism for this?

port:llvm-14: Add patch 0021-fix-find_dependency.patch to portfile.

---

docker/Dockerfile.ubuntu.vcpkg

More specifically, objects compiled with clang-14 cannot be linked with
objects compiled with clang-10 due to PIE and relocations

default back to clang-10 because things broke

---

.github/workflows/vcpkg_docker_arm64.yml

https://github.com/lifting-bits/cxx-common/blob/master/.github/workflows/vcpkg_ci_aws_arm64.yml#L74
referenced image expects arch_docker instead of arch

pushed image should use arch_docker instead of arch

---

dependencies.txt

Adds fulltext text indexing support to SQLite3. The fts5 module is the latest version for fulltext searching.

Add fts5 module to sqlite3

---

ports/llvm-15/0027-unknown-attrs-as-annotations.patch
ports/llvm-15/portfile.cmake
ports/llvm-15/vcpkg.json

Added patch for clang 15.0.6 that adds a flag to treat unknown attributes as annotation attributes in semantic analysis. By default clang still warns on and ignores unknown attributes. With the command line flag `-funknown-attrs-as-annotate` , it will treat unknown attributes on types and declarations as annotate_type or annotate attributes with the annotation string literal being equal to the unknown attribute and the other arguments being passed as arguments to the annotation attribute. This occurs in the semantic analysis stage (the ParsedAttributes will still have UnknownAttr as their kind).

Added clang flag to treat unknown attributes as annotation attributes

---

.github/workflows/vcpkg_docker_amd64.yml
docker/Dockerfile.ubuntu.vcpkg
docker/build.sh

~DO NOT MERGE UNTIL #1018 passes~
New naming scheme appends `-v#` to the image name. The tag part is not changed
Removed Docker Hub pushes. Now we use ghcr.io for both images.
Use GCC for cross-compilation on Linux because Ubuntu and vcpkg have better support for cross-compilation when using GCC

Docker image v2

---

ports/llvm-16/0029-Do-not-attempt-macro-expansion-on-invalid-sourceloc.patch
ports/llvm-16/portfile.cmake

Clang 16 added a semantic check for flexible array members that relies on grabbing sourceloc info for array types that are the last member of a union. If the sourceloc info is empty `dyn_cast<IntegerLiteral>(CTL.getSizeExpr())` will crash because getSizeExpr will be null and dyn_cast asserts a nonnulll input. Another plausible fix would be to do dyn_cast_or_null here but that would result in false. Still determining the best patch/testing

Add llvm-16 patch to not crash on invalid sourcelocs

---

.github/workflows/vcpkg_ci_amd64.yml

Docker image version technically matters for the release artifacts themselves, but we already version them with cxx-common version.
This change reduces churn in downstream

Remove Docker image version from release artifact name

---

README.md
build_dependencies.sh

Only upgrade ports that are specified. Also ask the user if they're sure they want to upgrade.
Should prevent accidentally deleting/rebuilding LLVM if it's out of date or if trying to upgrade a port it depends on.

Improve port upgrading experience

---

.github/workflows/vcpkg_docker_amd64.yml
.github/workflows/vcpkg_release.yml
README.md
vcpkg_info.txt

Better reproducibility because a vcpkg branch/tag can be updated from under you

Pin vcpkg commit

---

ports/llvm-17/portfile.cmake
ports/llvm-17/vcpkg.json
vcpkg_info.txt

Also update vcpkg to 2023.10.19 tag

Update to LLVM 17.0.4 and bump vcpkg
